apiVersion: v1
kind: Secret
metadata:
  name: repo-retrogame-infrastructure
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/retrogamecloud/infrastructure.git
  username: git
  password: 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
