apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://retrogamehub.games/argocd
  
  # GitHub OAuth configuration
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23li1po0fBSpoAPweT
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: retrogamecloud
        loadAllGroups: false
        teamNameField: slug
        useLoginAsID: false
