apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # GitHub OAuth Client Secret (dedicated ArgoCD OAuth App)
  dex.github.clientSecret: "eee8350a40817bf1758c6dc287acfc5c6840af4d"
