apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    apiURL: https://hooks.slack.com/services/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

  template.app-deployed: |
    message: |
      {
        "text": "✅ *Aplicación Desplegada*",
        "attachments": [{
          "color": "good",
          "fields": [
            {"title": "Aplicación", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Namespace", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
            {"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true},
            {"title": "Revisión", "value": "{{.app.status.sync.revision}}", "short": false}
          ]
        }]
      }

  template.app-sync-failed: |
    message: |
      {
        "text": "❌ *Sync Fallido*",
        "attachments": [{
          "color": "danger",
          "fields": [
            {"title": "Aplicación", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Namespace", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Fase", "value": "{{.app.status.operationState.phase}}", "short": true},
            {"title": "Error", "value": "{{.app.status.operationState.message}}", "short": false}
          ]
        }]
      }

  template.app-health-degraded: |
    message: |
      {
        "text": "⚠️ *Aplicación Degradada*",
        "attachments": [{
          "color": "warning",
          "fields": [
            {"title": "Aplicación", "value": "{{.app.metadata.name}}", "short": true},
            {"title": "Namespace", "value": "{{.app.spec.destination.namespace}}", "short": true},
            {"title": "Health Status", "value": "{{.app.status.health.status}}", "short": true},
            {"title": "Sync Status", "value": "{{.app.status.sync.status}}", "short": true},
            {"title": "Mensaje", "value": "{{.app.status.health.message}}", "short": false}
          ]
        }]
      }

  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'

  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']

  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'

  subscriptions: |
    - recipients:
      - slack:argocdretrogame
      triggers:
      - on-deployed
      - on-sync-failed
      - on-health-degraded
