apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "SLACK_BOT_TOKEN_AQUI"  # Reemplazar con el token real de Slack Bot
