apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base

patches:
  - target:
      kind: Deployment
      name: backend-deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env/2/value
      - op: add
        path: /spec/template/spec/containers/0/env/2/valueFrom
        value:
          secretKeyRef:
            name: postgres-credentials
            key: DATABASE_URL
      - op: remove
        path: /spec/template/spec/containers/0/env/3/value
      - op: add
        path: /spec/template/spec/containers/0/env/3/valueFrom
        value:
          secretKeyRef:
            name: jwt-secret
            key: JWT_SECRET
