apiVersion: v1
data:
  GF_AUTH_GITHUB_CLIENT_ID: T3YyM2xpazJjZko5UmVNS280YzE=
  GF_AUTH_GITHUB_CLIENT_SECRET: ZDhkY2U0MmY3ZjgzMzYwNTRiNjEzNTM1MjY0Y2YyOWM0YzY1ODBkYQ==
kind: Secret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
