name: Notify Docs - Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'argocd/**/*.yaml'
      - 'kong/**/*.yml'
      - 'terraform/**/*.tf'

jobs:
  notify-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs sync
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/retrogamecloud/docs/dispatches \
            -d '{"event_type":"infrastructure-updated"}'
